<?php

require("koneksi.php");
//include "c_klub.php";
//include "c_pertandingan.php";
//include "c_klasemen.php";
//$klub = new c_klub("Barcelona", "Camp Nou", "Denny S", "0");
//$klub->addKlub();
//$klub = new c_klub("Madrid", "Bernabeu", "Billy K", "0");
//$klub->addKlub();
//$klub = new c_klub("PSG", "Paris", "Richo W", "0");
//$klub->addKlub();
//$klub = new c_klub("Arsenal", "London", "Auryn S", "0");
//$klub->addKlub();
//$klub = new c_klub("Arema", "Kanjuruhan", "Alfons A", "0");
//$klub->addKlub();
//$klub = new c_klub("Juventus", "Turin", "Alucard", "0");
//$klub->addKlub();
//$jadwal = new m_jadwal('Arema','Arsenal','M1','19-12-2022');
//$jadwal->addJadwal();
//$jadwal2 = new c_jadwal('Barcelona','Juventus','M2','19-12-2022');
//$jadwal2->addJadwal();
//$jadwal3 = new c_jadwal('Madrid','PSG','M3','19-12-2022');
//$jadwal3->addJadwal();
//$jadwal4 = new c_jadwal('Arema','Barcelona','M4','19-12-2022');
//$jadwal4->addJadwal();
//$jadwal5 = new c_jadwal('Arsenal','Madrid','M5','19-12-2022');
//$jadwal5->addJadwal();
//$jadwal6 = new c_jadwal('Juventus','PSG','M6','19-12-2022');
//$jadwal6->addJadwal();
//$jadwal7 = new c_jadwal('Arema','Juventus','M7','19-12-2022');
//$jadwal7->addJadwal();
//$jadwal8 = new c_jadwal('Arsenal','PSG','M8','19-12-2022');
//$jadwal8->addJadwal();
//$jadwal9 = new c_jadwal('Madrid','Juventus','M9','19-12-2022');
//$jadwal9->addJadwal();
//$jadwal10 = new c_jadwal('Arsenal','Juventus','M10','19-12-2022');
//$jadwal10->addJadwal();
//$jadwal10 = new c_jadwal('Arema','PSG','M11','19-12-2022');
//$jadwal10->addJadwal();
//$jadwal10 = new c_jadwal('Arema','Barcelona','M12','19-12-2022');
//$jadwal10->addJadwal();
//$jadwal10 = new c_jadwal('Arsenal','Barcelona','M13','19-12-2022');
//$jadwal10->addJadwal();
//$jadwal10 = new c_jadwal('PSG','Barcelona','M14','19-12-2022');
//$jadwal10->addJadwal();

//$pertandingan = new c_pertandingan('M2','Barcelona','Juventus',3,1);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M3','Madrid','PSG',1,0);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M4','Arema','Barcelona',2,2);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M5','Arsenal','Madrid',5,3);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M6','Juventus','PSG',2,4);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M7','Arema','Juventus',0,2);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M8','Arsenal','PSG',4,1);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M9','Madrid','Juventus',1,3);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M10','Arsenal','Juventus',2,3);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M11','Arema','PSG',2,4);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M12','Arema','Barcelona',7,4);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M13','Arsenal','Barcelona',1,1);
//$pertandingan->addPoint();
//$pertandingan = new c_pertandingan('M14','PSG','Barcelona',1,1);
//$pertandingan->addPoint();
//$klub = new c_klub('null', 'null','null','null');
//$klub ->getKlub();

//$klasemen2 = new c_klasemen();
//$klasemen2->getKlasemen();